import { MigrateDownArgs, MigrateUpArgs, sql } from '@payloadcms/db-postgres'

// Generated by `pnpm migrate:create localize-changelog`, then edited by hand: the generated
// version dropped title/summary/body without copying them. Existing content becomes the
// default locale ('en'); other locales fall back to it until translated.
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  CREATE TYPE "public"."_locales" AS ENUM('en', 'ru');
  CREATE TABLE "changelog_locales" (
  	"title" varchar NOT NULL,
  	"summary" varchar NOT NULL,
  	"body" jsonb,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );

  ALTER TABLE "changelog_locales" ADD CONSTRAINT "changelog_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."changelog"("id") ON DELETE cascade ON UPDATE no action;
  CREATE UNIQUE INDEX "changelog_locales_locale_parent_id_unique" ON "changelog_locales" USING btree ("_locale","_parent_id");

  INSERT INTO "changelog_locales" ("title", "summary", "body", "_locale", "_parent_id")
    SELECT "title", "summary", "body", 'en', "id" FROM "changelog";

  ALTER TABLE "changelog" DROP COLUMN "title";
  ALTER TABLE "changelog" DROP COLUMN "summary";
  ALTER TABLE "changelog" DROP COLUMN "body";`)
}

// Keeps the English content (or any translation if English is missing); other translations are lost.
export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  ALTER TABLE "changelog" ADD COLUMN "title" varchar;
  ALTER TABLE "changelog" ADD COLUMN "summary" varchar;
  ALTER TABLE "changelog" ADD COLUMN "body" jsonb;

  UPDATE "changelog" AS c SET "title" = l."title", "summary" = l."summary", "body" = l."body"
    FROM (
      SELECT DISTINCT ON ("_parent_id") "_parent_id", "title", "summary", "body"
      FROM "changelog_locales"
      ORDER BY "_parent_id", ("_locale" = 'en') DESC, "id"
    ) AS l
    WHERE l."_parent_id" = c."id";
  UPDATE "changelog" SET "title" = '' WHERE "title" IS NULL;
  UPDATE "changelog" SET "summary" = '' WHERE "summary" IS NULL;

  ALTER TABLE "changelog" ALTER COLUMN "title" SET NOT NULL;
  ALTER TABLE "changelog" ALTER COLUMN "summary" SET NOT NULL;
  DROP TABLE "changelog_locales" CASCADE;
  DROP TYPE "public"."_locales";`)
}
